# copied from https://github.com/ubuntu/yaru/blob/master/.github/workflows/open-pr-on-changes.yaml
name: Update PR on upstream changes
on:
  push:
    paths:
      - '.github/workflows/open-pr-on-changes.yaml'
  schedule:
    - cron: '8 0 * * *'

jobs:
  refresh-upstream:
    name: Check for upstream theme related changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildenv:
          [
            {
              project: GNOME Shell,
              repo: 'https://gitlab.gnome.org/GNOME/gnome-shell.git',
              upstreambranch: main,
              localbranch: gnome-shell,
              projectdir: gnome-shell,
              src: data/theme,
              dest: gtk/upstream/gnome-shell
            },
            {
              project: GTK3,
              repo: 'https://github.com/lassekongo83/adw-gtk3.git',
              upstreambranch: main,
              localbranch: gtk3,
              projectdir: adw-gtk3,
              src: gtk/src/adw-gtk3/gtk-3.0,
              dest: gtk/upstream/gtk-3.0
            },
            {
              project: GTK4,
              repo: 'https://gitlab.gnome.org/GNOME/libadwaita.git',
              upstreambranch: main,
              localbranch: gtk4,
              projectdir: libadwaita,
              src: src/stylesheet,
              dest: gtk/upstream/gtk-4.0
            }
          ]
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      - name: Download from ${{ matrix.buildenv.repo }}, on branch ${{ matrix.buildenv.upstreambranch }}
        id: checknewupstream
        run: |
          hasModif="false"
          pushd /tmp
          git clone --branch ${UPSTEAM_BRANCH} --depth 1 ${UPSTREAM_REPO_URL}
          popd
          rm -rf ${DEST}
          cp -a /tmp/${PROJECT_DIR}/${SRC} ${DEST}
          MODIFIED=$(git status --porcelain)
          if [ -n "$MODIFIED" ]; then
            hasModif="true"
          fi
          echo "::set-output name=modified::${hasModif}"
        env:
          UPSTREAM_REPO_URL: ${{ matrix.buildenv.repo }}
          UPSTEAM_BRANCH: ${{ matrix.buildenv.upstreambranch }}
          SRC: ${{ matrix.buildenv.src }}
          DEST: ${{ matrix.buildenv.dest }}
          PROJECT_DIR: ${{ matrix.buildenv.projectdir }}
      - name: Create or update Pull Request
        if: steps.checknewupstream.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: new upstream snapshot for ${{ matrix.buildenv.project }}'
          title: Auto update new upstream snapshot for ${{ matrix.buildenv.project }}
          labels: automated pr, new upstream
          body: '[New upstream ${{ matrix.buildenv.project }} changes](https://github.com/lonr/adwaita-one-dark/actions?query=workflow%3A%22Update+PR+on+upstream+changes%22) by GitHub Action'
          branch: upstream-${{ matrix.buildenv.localbranch }}-update
          token: ${{ secrets.GITHUB_TOKEN }}
